### ISSUE TITLE
Class under the namespace.

### ISSUE THREAD

**Issue by kissy2go** [kazuooooo/Zengin_Bank_Gem#3]
このGemで宣言されるクラスは、すべて`Zengin`の名前空間以下に作成されるべき
`::Bank`など、Gemを利用する側で同じクラスが宣言されると、意図しない動作をする可能性がある

**Comment by kazuooooo** [comment]
指摘の通りと思います。
こちらのコミットで修正しました。
0696b023d3dce5dd5b9d32e7cc54dd9206f45533

**Comment by kissy2go** [comment]
:+1:
