### ISSUE TITLE
Unify namespace.

### ISSUE THREAD

**Issue by kissy2go** [kazuooooo/Zengin_Bank_Gem#4]
名前空間が統一されていない
- `lib/zengin_bank_gem.rb`では`Zengin`
- `lib/zengin_bank_gem/version.rb`では`ZenginBankGem`

Gem名`zengin_bank_gem`から推測される名前空間は`ZenginBankGem`

**Comment by kazuooooo** [comment]
こちらも指摘の通り修正するべきと思いましたので修正しました
7dda126203f1947d420abb20b08e2409a85f27f9
